export const ERROR_CODES = {
  // General
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",

  // Scraper/Cache
  CACHE_FETCH_FAILED: "CACHE_FETCH_FAILED",
  CACHE_HASH_FAILED: "CACHE_HASH_FAILED",
  CACHE_INSERT_FAILED: "CACHE_INSERT_FAILED",

  // Schema
  SCHEMA_PARSE_FAILED: "SCHEMA_PARSE_FAILED",

  // DB
  DB_INSERT_FAILED: "DB_INSERT_FAILED",
  DB_QUERY_FAILED: "DB_QUERY_FAILED",

  // FIRECRAWL
  FC_MARKDOWN_FAILED: "FC_MARKDOWN_FAILED",
  FC_LINKS_FAILED: "FC_LINKS_FAILED",
  FC_MAP_FAILED: "FC_MAP_FAILED",

  // AI
  AI_OBJECT_CREATION_FAILED: "AI_OBJECT_CREATION_FAILED",
} as const;

export type ERROR_CODE = typeof ERROR_CODES[keyof typeof ERROR_CODES];
